# 01 · Acquire raw data
27 cerebellum runs (PRJNA875066 aging + PRJNA946653 rejuvenation), paired-end Illumina.
Downloads are **resumable and idempotent**: re-run any cell after an interruption.

Launch Jupyter from the repo root with `pixi run jupyter lab`.

In [1]:
import sys; sys.path.insert(0, '../scripts')
import helpers as h
runs = h.load_runs()
h.status(runs)

                  group  sra_GB  quantified
SRR
SRR21355392   aging 3mo    1.88       False
SRR21355388   aging 3mo    1.94       False
SRR21355401   aging 3mo    1.67       False
SRR21355396   aging 3mo    3.03       False
SRR21355390  aging 18mo    3.23       False
SRR21355386  aging 18mo    1.13       False
SRR21355398  aging 18mo    0.78       False
SRR21355394  aging 18mo    0.95       False
SRR21355389  aging 21mo    1.96       False
SRR21355385  aging 21mo    1.89       False
SRR21355397  aging 21mo    1.66       False
SRR21355393  aging 21mo    1.16       False
SRR23914577          AL    3.23       False
SRR23914574          AL    2.67       False
SRR23914572          AL    1.67       False
SRR23914571          AL    1.89       False
SRR23914455         PBS    3.30       False
SRR23914452         PBS    1.79       False
SRR23914450         PBS    2.61       False
SRR23914454         YMP    2.71       False
SRR23914453         YMP    1.69       False
SRR23914451         YMP    2.07       False
SRR23914579         aDR    1.74       False
SRR23914578         aDR    1.31       False
SRR23914576         aDR    1.62       False
SRR23914575         aDR    3.08       False
SRR23914573         aDR    1.53       False

## Download `.sra` (~50 GB total)
`prefetch` + `vdb-validate` per run. Logs: `results/logs/<SRR>.log`. `.sra` files are kept (small, canonical); FASTQs are made temporary in notebook 02.

In [2]:
h.download_all(runs)

all 27 runs present

In [3]:
s = h.status(runs); print(f"{s.sra_GB.notna().sum()}/27 runs, {s.sra_GB.sum():.1f} GB")
s

27/27 runs, 54.2 GB

                  group  sra_GB  quantified
SRR
SRR21355392   aging 3mo    1.88       False
SRR21355388   aging 3mo    1.94       False
SRR21355401   aging 3mo    1.67       False
SRR21355396   aging 3mo    3.03       False
SRR21355390  aging 18mo    3.23       False
SRR21355386  aging 18mo    1.13       False
SRR21355398  aging 18mo    0.78       False
SRR21355394  aging 18mo    0.95       False
SRR21355389  aging 21mo    1.96       False
SRR21355385  aging 21mo    1.89       False
SRR21355397  aging 21mo    1.66       False
SRR21355393  aging 21mo    1.16       False
SRR23914577          AL    3.23       False
SRR23914574          AL    2.67       False
SRR23914572          AL    1.67       False
SRR23914571          AL    1.89       False
SRR23914455         PBS    3.30       False
SRR23914452         PBS    1.79       False
SRR23914450         PBS    2.61       False
SRR23914454         YMP    2.71       False
SRR23914453         YMP    1.69       False
SRR23914451         YMP    2.07       False
SRR23914579         aDR    1.74       False
SRR23914578         aDR    1.31       False
SRR23914576         aDR    1.62       False
SRR23914575         aDR    3.08       False
SRR23914573         aDR    1.53       False

## Verify integrity
Checksums every `.sra`; an empty list means all 27 are intact (a few minutes).

In [4]:
h.validate_all(runs)

validate:   0%|          | 0/27 [00:00<?, ?it/s]

[]